---
version: '2.2'
services:

  command-handler:
    build:
      context: command-handler
    container_name: command-handler
    environment:
      KAFKA_BROKERS: "kafka:19092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    mem_limit: 300m
    restart: always

  projector:
    build:
      context: projector
    container_name: projector
    environment:
      KAFKA_BROKERS: "kafka:19092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    mem_limit: 300m
    restart: always

  graphql-endpoint:
    build:
      context: graphql-endpoint
    container_name: graphql-endpoint
    ports:
      - "8888:8888"
    depends_on:
      - command-handler
      - projector
    environment:
      KAFKA_BROKERS: "kafka:19092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      PEDESTAL_HOST: 0.0.0.0
    mem_limit: 400m
    restart: always

  frontend:
    build:
      context: frontend
    container_name: frontend
    ports:
      - "8181:80"
    depends_on:
      - graphql-endpoint
    environment:
      - NGINX_PORT=80
    restart: always
