@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

actor client as cl #White
component "query-bus" as qb #Yellow
component "command-bus" as cb #Yellow
component "schema-provider" as sp #Yellow
component "kafka" as kc #LightGrey

cl <-right-> sp :request account\lvia graphql\nneeds token and iban
sp --> qb: gets existing\nuser
sp --> cb: crate new user, and\nbank account for user
qb <-down-> kc: send queries\nreceives feedback
cb <--> kc: send commands\nreceives feedback

@enduml