@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

database [projection db] as pgt #LightBlue
database [aggregate db] as pgb #LightBlue
[Kafka] as ka #LightGrey
[Command handler] as ch #Yellow
[Projector] as pr #Yellow
[GraphQL endpoint] as ge #Yellow
[Frontend server] as fs #LightGreen
[BKES] as bk #LightGreen
[BKE-lane] as bl #LightGreen
actor client as cl #White

ge <--> bl
cl <-left- fs
cl <--> ge
ch <--> bl
pgt <-- ka
ch <--> pgb
pr <--> pgt
pr <--> bl
pgb <-right-> bk
bk <-right-> ka

@enduml