@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

component "command-bus" as cb #Yellow
component kafka as kc #LightGrey
actor client as cl #White
component "schema-provider" as sp #Yellow
rectangle "command-handler" as ch #White

cl <-right-> sp :request transfer by using\la GraphQL mutation
sp --> cb :executes function\nresulting in a\n MoneyTransferCommand\nand awaits the result
cb <--> kc: send commands\nreceives feedback
ch <-right-> kc :handles the saga\nwill end with a\nMarkTransferCompletedCommand\nor MarkTransferFailedCommand

@enduml