@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

database [projection db] as pgt #LightBlue
database [aggregate db] as pgb #LightBlue
[Kafka] as ka #LightGrey
[Command handler] as ch #Yellow
[Projector] as pr #Yellow
[GraphQL endpoint] as ge #Yellow
[Frontend server] as fs #LightGreen
[BKES] as bk #LightGreen
actor client as cl #White

ge <-right-> ka
cl <-up- fs
cl <--> ge
ch <-up-> ka
pr <--> ka
ch <-left-> pgb
pr <-up-> pgt
ch <-right-> bk
bk <-up-> ka
@enduml