@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

database [projection db] as pgt #LightBlue
database [aggregate db] as pgb #LightBlue
[Kafka] as ka #LightGrey
[Command handler] as ch #Yellow
[Projector] as pr #Yellow
[GraphQL endpoint] as ge #Yellow
[Frontend server] as fs #LightGreen
actor client as cl #White

ge <-right-> ka
cl <- fs
cl <---> ge
ch <-up-> ka
pr <--> ka
ch <-right-> pgb
pr <-right-> pgt
@enduml