@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

package "nl.openweb.projector.core.clj" #White{
    component "user-query-handler" as uch #Yellow
    component "user-event-handler" as ueh #Yellow
    component "bank-query-handler" as bch #Yellow
    component "bank-event-handler" as beh #Yellow
}
package "nl.openweb.projector.db.clj" #White{
    database "bank-accounts" as badb #LightBlue
    database "users" #LightBlue
}
component Kafka as kc #F26724

uch --> users :check status
ueh --> users :add/update projection
bch --> badb :check status
beh --> badb :add/update projection
kc --> ueh :routes events
kc --> beh :routes events
beh --> kc :transactions
kc --> uch :routes queries
kc --> bch :routes queries
kc <-- uch :feedback
kc <-- bch :feedback


@enduml