@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

actor client as cl #White
component "query-bus" as qb #Yellow
component consumer as c #Yellow
component kafka as kc #LightGrey
component "schema-provider" as sp #Yellow

cl <-> sp :queries or subscribe\lto transactions
sp <-> qb :issue queries
c <- kc :consumes\nTransactionHappenedEvent
c --> sp :send transaction\nfor active subscriptions
qb <-up-> kc: send queries\nreceives feedback


@enduml